# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-04 13:22
from __future__ import unicode_literals

import analyse.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyse', '0002_auto_20170407_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='album_logo',
            field=models.FileField(upload_to=analyse.models.upload_location),
        ),
        migrations.AlterField(
            model_name='data',
            name='uploader',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
